# -*- coding: utf-8 -*-
"""Hackathon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GedlThP5fchsxUmETfAwnG0b1m3c6pDF
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn .model_selection import train_test_split
from flask import Flask, redirect, url_for, request, render_template

def get_prediction_proba(user):
  df = pd.read_csv('dataset (1).csv',names=['Date','Water Used(Litres/day)','Water saved(Litres/day)'])
  df=df[:11721]
  df['Water Used(Litres/day)'].max()
  df['Water saved(Litres/day)'].max()
  x=df[['Water Used(Litres/day)']]
  y=df[['Water saved(Litres/day)']]
  
  x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 101)
  
  lr = LinearRegression()
  
  lr.fit(x_train,y_train)
  
  lr.score(x_test,y_test)
  
  lis=[]
  lis.append(user)
  data = pd.DataFrame({"Water Used(Litres/day)":lis})
  y_pred1 = lr.predict(data)
  if(y_pred1<0):
    water=lis[0]
    y_pred1[0][0]=(20/100)*lis[0]
  return y_pred1[0][0]


app = Flask(__name__)


@app.route('/input/<name>')
def display_name(name):
	return render_template('predict.html', output=name)




@app.route('/water_predictor' , methods = ['POST', 'GET'])
def hello_world():
	if request.method == 'POST':
		user = request.form['text']
		ex1 = int(user)
		probability = get_prediction_proba(ex1)
		
		sentence = "{:.2f}".format(probability)+" litres" 
		return redirect(url_for('display_name',name = sentence))

@app.route('/moreinfo')
def sav():
  return("""
  <head>
    <title>End page</title>
    <link rel="stylesheet" href="endd.css">

    <style>

    body{
        background-color : orange;
        background-size: 1500px 750px;
        text-align:center;
    }
    
    .h3{
            background-color: rgb(184,197,195);
            padding-top: 4px;
            padding-bottom: 4px;
            padding-left: 40px;
            border-style: solid;
            border-radius: 70px;
    }
    #a1{
        background-color: rgb(138, 153, 151);
            padding-top: 4px;
            padding-bottom: 4px;
            padding-left: 40px;
            border-style: double;
            
    }
    
    .h4{
        background-color: rgb(184,197,195);
        padding-top: 4px;
        padding-bottom: 4px;
        padding-left: 40px;
        border-style: solid;
        border-radius: 70px;
    }
    #a2{
    background-color: rgb(138, 153, 151);
        padding-top: 4px;
        padding-bottom: 4px;
        padding-left: 30px;
        border-style: double;
        
    }
    .h5{
        background-color: rgb(184,197,195);
        padding-top: 4px;
        padding-bottom: 4px;
        padding-left: 40px;
        border-style: solid;
        border-radius: 70px;
    }
    #a3{
    background-color: rgb(138, 153, 151);
        padding-top: 4px;
        padding-bottom: 4px;
        padding-left: 40px;
        border-style: double;
        
    }
    .h6{
        background-color: rgb(184,197,195);
        padding-top: 4px;
        padding-bottom: 4px;
        padding-left: 40px;
        border-style: solid;
        border-radius: 70px;
    }
    </style>
</head>
<body>
    <div class="h1">
        <h1><b>****BENEFITS OF RAINWATER HARVESTING****</b></h1>
    </div>
    <div class="h2">
        <h2>
            Rainwater harvesting has many benefits but the main one is that it is a sustainable water management practice that can be implemented by anyone on many different levels, from a simple rain barrel to a comprehensive rainwater harvesting system that integrates with an irrigation system or household plumbing.
        </h2>
    </div>
    
    <div class="h3">
        <h2 id="a1"><b>THE WATER CONSERVATION BENEFITS OF RAINWATER HARVESTING</b></h2>
        <br>
        <h3 id="b1">
            <li>The rainwater that falls on your roof and property is essentially free.  All it takes is a method to harvest it into a tank or cistern for later use.

            <br><br></li><li>Rainwater harvesting can be a great educational tool to get people to recognize their individual or household water usage.  This can get them to start conserving water in other areas around their home.
<br><br></li><li>For communities that rely on imported water to supply their needs, collecting rainwater that falls naturally in the community can reduce the need for imported water.
<br><br></li><li>Rainwater harvesting helps utilities reduce peak demands during summer months, saving treated water for more important and appropriate water uses.
<br><br></li><li>While rainwater can be a perfect primary water source for many uses and situations, it is also a great backup water supply for emergency situations.
        </h3>
    </div>
    <br>
    <div class="h4">
        <h2 id="a2"><b>
            THE ENVIRONMENTAL BENEFITS OF RAINWATER HARVESTING
        </b></h2>
        <h3>
            <li>Rainwater harvesting can reduce stormwater runoff from a property.  The elimination of runoff can reduce contamination of surface water with pesticides, sediment, metals, and fertilizers.
<br><br></li><li>By reducing stormwater runoff, rainwater harvesting can reduce a storm’s peak flow volume and velocity in local creeks, streams, and rivers, thereby reducing the potential for streambank erosion.
</li><br><br><li>Rainwater harvesting systems can be employed as simple and effective methods to meet a municipality’s stormwater management program requirements of individual properties.
</li><br><br><li>It is an excellent source of water for plants and landscape irrigation since it has no chemicals such as fluoride and chloramines (chlorine).
        </h3>
    </div>

    <br>
    <div class="h5">
        <h2 id="a3"><b>
            THE ECONOMIC BENEFITS OF RAINWATER HARVESTING
        </b></h2>
        <h3>
            <li>Collecting and using rainwater to replace municipal water use reduces your water bill
</li><br><br><li>Reducing municipal water use for areas such as irrigation reduces the amount of water that a municipality has to treat and pump.  This, in turn, reduces water service cost to a municipality.
</li><br><br><li>The widespread implementation of rainwater harvesting within a municipality’s service area can reduce the long-term water development needs of a city, allowing the city to use their existing water infrastructure investments more efficiently.  </li><br><br><li>The cost to the community to supply treated water is becoming more expensive every year. </li><br><br><li>The cost to construct dams, pipes, and treatment plants, not to mention the cost of maintenance and infrastructure replacement is huge. </li><br><br><li> As water users, the rate-payers in the community ultimately will foot this rising bill.  </li><br><br><li>Therefore, the practice of rainwater harvesting can reduce water demand and thus allow municipalities to provide potable water service at a lower cost.
</li><br><br><li>Designing and installing rainwater collection systems can provide sustainable jobs for the economy of the future.  The rainwater harvesting industry can become a leading employer in the green infrastructure movement.
</li><br><br><li>Rainwater stored onsite in a rainwater harvesting system can be available for wildfires and help protect the house and property.  Insurance companies can offer discounts for storing water onsite for fire protection.
        </h3>
    </div>
    <br><br>
   
</body>
  
""")


if __name__ == '__main__':
  app.debug = True
  app.run()
  app.run(debug = True)